[[main]]
  name = "External material"  # Title of the link.
  url = "en/teaching/Workshops"  # Widget Page folder name.
  weight = 4  # Position of the link in the navigation bar.

[[main]]
  name = "Tutorials"  # Title of the link.
  url = "en/teaching/Tutorials"  # Widget Page folder name.
  weight = 8  # Position of the link in the navigation bar.

[[main]]
  name = "Classes"  # Title of the link.
  url = "teaching/Classes"  # Widget Page folder name.
  weight = 12  # Position of the link in the navigation bar.
